// Code generated by "stringer -type MonitorType -trimprefix Type"; DO NOT EDIT.

package monitor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeHTTP-1]
}

const _MonitorType_name = "UnknownHTTP"

var _MonitorType_index = [...]uint8{0, 7, 11}

func (i MonitorType) String() string {
	if i < 0 || i >= MonitorType(len(_MonitorType_index)-1) {
		return "MonitorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MonitorType_name[_MonitorType_index[i]:_MonitorType_index[i+1]]
}
